server:
  port: 8080

spring:
  application:
    name: board-service
  datasource:
    url: jdbc:mariadb://localhost:3307/board_study
    username: root
    password: 1234

    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-jiniworld_demo
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    open-in-view: false
    defer-datasource-initialization: true